-- VERIFIED QUERY REFERENCE
-- QUERY: AML_EPISODE
-- QUESTION: How are AML product episodes built?
-- PRIMARY_KBT: 2
-- SECONDARY_KBTS: 
-- DIALECT: Databricks / Spark SQL
-- PURPOSE: The SQL pldlib stencil.episode generates: one row per patient x product x episode with start date, end dates 1-3, length, first SOB, first claim id and last-claim grace/lookback.
-- DATA_SOURCE: SHA (SHA_PTD)
-- TABLES: Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_SOB_BUSINESS_RULE_CHANGE_VAL_v2
-- METRICS: none
-- REUSABLE_COMPONENTS: episode roll-up from SOB rows, episode_first_sob, first_claim_id_drvd
-- KNOWN_ISSUE: Rendered from the pldlib source with the AML_LOT_SOB_EPISODE parameters. The notebook passes the sob_df temp view; the persisted SOB table holds the same rows and is used here. metric_ordering_by_clmns is passed by the notebook but ignored by pldlib. Writes Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_EPISODE_BUSINESS_RULE_CHANGE_VAL_v2.
-- SOURCE: scripts/Notebooks (rendered with the notebook's table-name globals; CREATE TABLE wrappers removed so the reference only reads).
-- USE: Reuse fully when the request matches, or copy relevant components into a new working query.
-- ADAPTATION: Correct documented issues in the working query and disclose material changes; do not overwrite this reference.

-- stencil.init(spark).episode(
--   src_input_tbl = sob_df
--   patient_gid_clmn = PATIENT_GID
--   product_name_clmn = FINAL_PRODUCT_NAME
--   metric_ordering_by_clmns = CLAIM_DATE, CLAIM_ID
--   claim_rnkn_partition_on_clmns = PATIENT_GID, FINAL_PRODUCT_NAME, EPISODE_NUM_DRVD
--   claim_rnkn_ordering_by_clmns = CLAIM_DATE, CLAIM_ID
--   claim_id_clmn = CLAIM_ID
--   episode_end_dts_clmns = EPISODE_END_DATE1_DRVD, EPISODE_END_DATE2_DRVD, EPISODE_END_DATE3_DRVD
--   claim_start_dt_clmn = CLAIM_DATE
--   drug_class_clmn = "NA"
--   dos_null_flag_clmns = DOS_NULL_FLAG, DOS_PAT_PRD_NULL_FLAG, DOS_PAT_PRD_EPSD_NULL_FLAG
-- )

-- SQL generated by pldlib (scripts/pldlib/source/businessLogic/businessLogic_episode.py) for exactly these parameters.
-- This is what the stencil call runs; the notebook persists its result as-is.
--------------------------------------------------
--Module Name :-   MABI_PLD_EPISODE_TBL
--Module description : - This module will create Episode details for the patient 
--Parameters required :- Databasename, Tablename, Episode End Date
--Created by :- ABHISAX
--Created on :- 30 Nov 2018
--Version History :- N/A
---------------------------------------------------

select PATIENT_GID,FINAL_PRODUCT_NAME,drug_class_epsd,ntb_rnk,ntb_flag,episode_num_drvd,episode_start_date_drvd,EPISODE_END_DATE1_DRVD, EPISODE_END_DATE2_DRVD, EPISODE_END_DATE3_DRVD,episode_length,episode_length_overlap,episode_first_sob,dos_wo_last_claim,dos_wo_last_claim_no_overlap,dos_last_claim,DOS_NULL_FLAG, DOS_PAT_PRD_NULL_FLAG, DOS_PAT_PRD_EPSD_NULL_FLAG,first_claim_id_drvd,last_claims_grace_drvd,last_claims_lookback_drvd

from
(
select PATIENT_GID,FINAL_PRODUCT_NAME,drug_class_epsd,grace_drvd,lookback_drvd,ntb_rnk,ntb_flag,episode_num_drvd,episode_start_date_drvd,EPISODE_END_DATE1_DRVD, EPISODE_END_DATE2_DRVD, EPISODE_END_DATE3_DRVD,episode_length,episode_length_overlap,dos_wo_last_claim,dos_wo_last_claim_no_overlap,dos_last_claim,DOS_NULL_FLAG, DOS_PAT_PRD_NULL_FLAG, DOS_PAT_PRD_EPSD_NULL_FLAG
,first_value(CLAIM_ID) over (partition by PATIENT_GID,FINAL_PRODUCT_NAME,episode_num_drvd order by clm_rnk) as first_claim_id_drvd

,first_value(sob_lvl7) over (partition by PATIENT_GID,FINAL_PRODUCT_NAME,episode_num_drvd order by clm_rnk) as episode_first_sob

,first_value(grace_drvd) over (partition by PATIENT_GID,FINAL_PRODUCT_NAME,episode_num_drvd order by clm_rnk desc) as last_claims_grace_drvd

,first_value(lookback_drvd) over (partition by PATIENT_GID,FINAL_PRODUCT_NAME,episode_num_drvd order by clm_rnk desc) as last_claims_lookback_drvd

from
(
select PATIENT_GID,FINAL_PRODUCT_NAME,drug_class_epsd,CLAIM_DATE,CLAIM_ID,grace_drvd,lookback_drvd,sob_lvl7,ntb_rnk,ntb_flag,episode_num_drvd,episode_start_date_drvd,EPISODE_END_DATE1_DRVD, EPISODE_END_DATE2_DRVD, EPISODE_END_DATE3_DRVD,episode_length,episode_length_overlap,dos_wo_last_claim,dos_wo_last_claim_no_overlap,dos_last_claim,DOS_NULL_FLAG, DOS_PAT_PRD_NULL_FLAG, DOS_PAT_PRD_EPSD_NULL_FLAG
,row_number() over (partition by PATIENT_GID, FINAL_PRODUCT_NAME, EPISODE_NUM_DRVD order by CLAIM_DATE, CLAIM_ID) as clm_rnk
from      
(
select PATIENT_GID,FINAL_PRODUCT_NAME,"NA" as drug_class_epsd,CLAIM_DATE,CLAIM_ID,grace_drvd,lookback_drvd,sob_lvl7,ntb_rnk,ntb_flag,episode_num_drvd,episode_start_date_drvd,EPISODE_END_DATE1_DRVD, EPISODE_END_DATE2_DRVD, EPISODE_END_DATE3_DRVD,episode_length,episode_length_overlap,dos_wo_last_claim,dos_wo_last_claim_no_overlap,dos_last_claim,DOS_NULL_FLAG, DOS_PAT_PRD_NULL_FLAG, DOS_PAT_PRD_EPSD_NULL_FLAG
from Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_SOB_BUSINESS_RULE_CHANGE_VAL_v2 as src
)bse
)sob_claim_rnkn
)epsd_dtls
group by PATIENT_GID,FINAL_PRODUCT_NAME,drug_class_epsd,ntb_rnk,ntb_flag,episode_num_drvd,episode_start_date_drvd,

EPISODE_END_DATE1_DRVD, EPISODE_END_DATE2_DRVD, EPISODE_END_DATE3_DRVD,episode_length,episode_length_overlap,episode_first_sob,dos_wo_last_claim,dos_wo_last_claim_no_overlap,dos_last_claim,DOS_NULL_FLAG, DOS_PAT_PRD_NULL_FLAG, DOS_PAT_PRD_EPSD_NULL_FLAG,first_claim_id_drvd,last_claims_grace_drvd,last_claims_lookback_drvd
order by PATIENT_GID,episode_start_date_drvd,FINAL_PRODUCT_NAME,episode_num_drvd
