-- VERIFIED QUERY REFERENCE
-- QUERY: AML_LOT_IC_INELIG
-- QUESTION: How is line of therapy assigned for IC Ineligible AML patients?
-- PRIMARY_KBT: 4
-- SECONDARY_KBTS: 
-- DIALECT: Databricks / Spark SQL
-- PURPOSE: IC Ineligible LoT: 11-product backbone CASE (HMAs -> 'HMA'), new line on gap > 90 days or backbone change, except VENCLEXTA <-> HMA; LOT = running SUM(LINE_CHANGE).
-- DATA_SOURCE: SHA (SHA_PTD)
-- TABLES: Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_BASIC_REGIMEN_BUSINESS_RULE_CHANGE_VAL_v2; Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_PATIENT_COHORT_BUSINESS_RULE_CHANGE_VAL_v2
-- METRICS: none
-- REUSABLE_COMPONENTS: IC_INELIG backbone CASE, 90-day gap test, VEN<->HMA exception
-- KNOWN_ISSUE: ic_inelig_cons_final is a temp view (all regimens kept; no consolidation, no minimum-length filter), inlined as a CTE. Writes Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_IC_INELIG_LOT_FINAL_BUSINESS_RULE_CHANGE_VAL_v2.
-- SOURCE: scripts/Notebooks (rendered with the notebook's table-name globals; CREATE TABLE wrappers removed so the reference only reads).
-- USE: Reuse fully when the request matches, or copy relevant components into a new working query.
-- ADAPTATION: Correct documented issues in the working query and disclose material changes; do not overwrite this reference.

WITH ic_inelig_cons_final AS (
SELECT *
FROM
(
    -- Smaller regimens were dropped earlier, now all the regimens are kept as it is
                                 
    SELECT *  
    --,CASE
      --  WHEN REGIMEN = 'RYDAPT' AND REGIMEN_LENGTH >= 14 THEN 1 --RYDAPT CLAIMS HAVE DOS OF 14/21 AS WELL
      --  WHEN REGIMEN_LENGTH >= 28 THEN 1
     --   ELSE 0
    --END AS SEL_FLAG
                                 
    FROM
    (   SELECT PATIENT_GID_RGMN AS PATIENT_GID,  REGIMEN, REGIMEN_START_DATE, REGIMEN_END_DATE,
        --SELECT PATIENT_GID_RGMN AS PATIENT_GID, NEW_RNK, REGIMEN, LVL, REGIMEN_START_DATE, REGIMEN_END_DATE,
        DATEDIFF(REGIMEN_END_DATE, REGIMEN_START_DATE) AS REGIMEN_LENGTH
        --FROM ic_inelig_cons5
         FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_BASIC_REGIMEN_BUSINESS_RULE_CHANGE_VAL_v2
 									WHERE PATIENT_GID_RGMN IN
 									(
 										SELECT DISTINCT PATIENT_GID_RGMN
 										FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_PATIENT_COHORT_BUSINESS_RULE_CHANGE_VAL_v2
 										WHERE PATIENT_INTENSITY_GROUP = 'IC_INELIG'
 									)
    )A
)A
                                 
--WHERE SEL_FLAG = 1
)
	
	SELECT *,
	SUM(LINE_CHANGE) OVER (PARTITION BY PATIENT_GID ORDER BY REGIMEN_START_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS LOT
	FROM
	(
		SELECT *,
		CASE
			WHEN REG_NUM = 1 THEN 1
			WHEN PREV_GAP > 90 THEN 1
			WHEN PREV_GAP <= 90 THEN
				CASE
					WHEN BACKBONE = PREV_BACKBONE THEN 0
					WHEN BACKBONE LIKE '%VENCLEXTA%' AND PREV_BACKBONE LIKE '%HMA%' THEN 0
					WHEN BACKBONE LIKE '%HMA%' AND PREV_BACKBONE LIKE '%VENCLEXTA%' THEN 0
					ELSE 1 --WHEN BACKBONE <> PREV_BACKBONE THEN 1
				END
		END AS LINE_CHANGE
		FROM
		(
			SELECT *,
			LAG(BACKBONE) OVER (PARTITION BY PATIENT_GID ORDER BY REGIMEN_START_DATE) AS PREV_BACKBONE,
			DATEDIFF(REGIMEN_START_DATE, LAG(REGIMEN_END_DATE) OVER (PARTITION BY PATIENT_GID ORDER BY REGIMEN_START_DATE)) AS PREV_GAP
			FROM
			(
				SELECT PATIENT_GID, REGIMEN, 
				TO_DATE(REGIMEN_START_DATE) AS REGIMEN_START_DATE, 
				TO_DATE(REGIMEN_END_DATE) AS REGIMEN_END_DATE, REGIMEN_LENGTH,
				ROW_NUMBER() OVER (PARTITION BY PATIENT_GID ORDER BY REGIMEN_START_DATE) AS REG_NUM,
				CASE
          
					WHEN REGIMEN RLIKE 'VENCLEXTA' THEN 'VENCLEXTA'
					WHEN REGIMEN RLIKE 'TIBSOVO' THEN 'TIBSOVO'
					WHEN REGIMEN RLIKE 'REZLIDHIA' THEN 'REZLIDHIA'
					WHEN REGIMEN RLIKE 'IDHIFA' THEN 'IDHIFA'
					WHEN REGIMEN RLIKE 'XOSPATA' THEN 'XOSPATA'
					WHEN REGIMEN RLIKE 'DAURISMO' THEN 'DAURISMO'
					--WHEN REGIMEN RLIKE 'RYDAPT' THEN 'RYDAPT'   --REMOVING RYDAPT AND MYLOTARG FROM IC INELIG BACKBONE HIERARCHY
					--WHEN REGIMEN RLIKE 'MYLOTARG' THEN 'MYLOTARG'
					WHEN REGIMEN RLIKE 'L-DAC' THEN 'L-DAC'
					WHEN REGIMEN RLIKE 'AZACITIDINE' THEN 'HMA'
					WHEN REGIMEN RLIKE 'DECITABINE' THEN 'HMA'
					WHEN REGIMEN RLIKE 'INQOVI' THEN 'HMA'		--ADDING INQOVI AND ONUREG IN IC INELIG BACKBONE HIERARCHY
					WHEN REGIMEN RLIKE 'ONUREG' THEN 'HMA'
				END AS BACKBONE
				FROM ic_inelig_cons_final
			)A
		)A
	)
