-- VERIFIED QUERY REFERENCE
-- QUERY: AML_LOT_IC_ELIG
-- QUESTION: How is line of therapy assigned for IC Eligible AML patients?
-- PRIMARY_KBT: 4
-- SECONDARY_KBTS: 
-- DIALECT: Databricks / Spark SQL
-- PURPOSE: IC Eligible LoT: 28-product backbone CASE (S-DAC/HI-DAC grouped, HMAs -> 'HMA'), same gap / backbone / VEN<->HMA rules.
-- DATA_SOURCE: SHA (SHA_PTD)
-- TABLES: Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_BASIC_REGIMEN_BUSINESS_RULE_CHANGE_VAL_v2; Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_PATIENT_COHORT_BUSINESS_RULE_CHANGE_VAL_v2
-- METRICS: none
-- REUSABLE_COMPONENTS: IC_ELIG backbone CASE (branch order = hierarchy)
-- KNOWN_ISSUE: ARSENIC_TRIOXIDE regimens stay in the table; exclude downstream with ARSENIC_FLG = 1. Writes Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_IC_ELIG_LOT_FINAL_BUSINESS_RULE_CHANGE_VAL_v2.
-- SOURCE: scripts/Notebooks (rendered with the notebook's table-name globals; CREATE TABLE wrappers removed so the reference only reads).
-- USE: Reuse fully when the request matches, or copy relevant components into a new working query.
-- ADAPTATION: Correct documented issues in the working query and disclose material changes; do not overwrite this reference.

SELECT *,
	SUM(LINE_CHANGE) OVER (PARTITION BY PATIENT_GID_RGMN ORDER BY REGIMEN_START_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS LOT
	FROM
	(
		SELECT *,
		CASE
			WHEN REG_NUM = 1 THEN 1
			WHEN PREV_GAP > 90 THEN 1
			WHEN PREV_GAP <= 90 THEN
				CASE
					WHEN BACKBONE = PREV_BACKBONE THEN 0	
					WHEN BACKBONE LIKE '%VENCLEXTA%' AND PREV_BACKBONE LIKE '%HMA%' THEN 0
					WHEN BACKBONE LIKE '%HMA%' AND PREV_BACKBONE LIKE '%VENCLEXTA%' THEN 0
					ELSE 1 											
				END
		END AS LINE_CHANGE
		FROM
		(
			SELECT *,
			LAG(BACKBONE) OVER (PARTITION BY PATIENT_GID_RGMN ORDER BY REGIMEN_START_DATE) AS PREV_BACKBONE,
			DATEDIFF((REGIMEN_START_DATE), LAG(REGIMEN_END_DATE) OVER (PARTITION BY PATIENT_GID_RGMN ORDER BY REGIMEN_START_DATE)) AS PREV_GAP
			FROM
			(
				SELECT PATIENT_GID_RGMN, REGIMEN, REGIMEN_START_DATE, REGIMEN_END_DATE, 
				DATEDIFF((REGIMEN_END_DATE) , (REGIMEN_START_DATE)) AS REG_LEN,
				ROW_NUMBER() OVER (PARTITION BY PATIENT_GID_RGMN ORDER BY REGIMEN_START_DATE) AS REG_NUM,
				CASE
					WHEN REGIMEN LIKE '%HI-DAC%' OR REGIMEN LIKE '%S-DAC%' THEN 'S-DAC/HI-DAC'
					WHEN REGIMEN LIKE '%VANFLYTA%' THEN 'VANFLYTA'
					WHEN REGIMEN LIKE '%VYXEOS%' THEN 'VYXEOS'
					WHEN REGIMEN LIKE '%CYCLOPHOSPHAMIDE%' THEN 'CYCLOPHOSPHAMIDE'
					WHEN REGIMEN LIKE '%VINCRISTINE%' THEN 'VINCRISTINE'
					WHEN REGIMEN LIKE '%FLUDARABINE%' THEN 'FLUDARABINE'
					WHEN REGIMEN LIKE '%IDARUBICIN%' THEN 'IDARUBICIN'
					WHEN REGIMEN LIKE '%DAUNORUBICIN%' THEN 'DAUNORUBICIN'
					WHEN REGIMEN LIKE '%MITOXANTRONE%' THEN 'MITOXANTRONE'
					WHEN REGIMEN LIKE '%RYDAPT%' THEN 'RYDAPT'
					WHEN REGIMEN LIKE '%VENCLEXTA%' THEN 'VENCLEXTA'
					WHEN REGIMEN LIKE '%XOSPATA%' THEN 'XOSPATA'
					WHEN REGIMEN LIKE '%TIBSOVO%' THEN 'TIBSOVO'
					WHEN REGIMEN LIKE '%REZLIDHIA%' THEN 'REZLIDHIA'
					WHEN REGIMEN LIKE '%IDHIFA%' THEN 'IDHIFA'
					WHEN REGIMEN LIKE '%MYLOTARG%' THEN 'MYLOTARG'
					WHEN REGIMEN LIKE '%DAURISMO%' THEN 'DAURISMO'
					WHEN REGIMEN LIKE '%ONUREG%' THEN 'HMA'    --ONUREG AND INQOVI ARE TREATED AS HMAs
					WHEN REGIMEN LIKE '%INQOVI%' THEN 'HMA'
					WHEN REGIMEN LIKE '%NEXAVAR%' THEN 'NEXAVAR'
					WHEN REGIMEN LIKE '%ETOPOSIDE%' THEN 'ETOPOSIDE'
					WHEN REGIMEN LIKE '%CLADRIBINE%' THEN 'CLADRIBINE'
					WHEN REGIMEN LIKE '%CLOFARABINE%' THEN 'CLOFARABINE'
					WHEN REGIMEN LIKE '%AZACITIDINE%' OR REGIMEN LIKE '%DECITABINE%' THEN 'HMA'
					WHEN REGIMEN LIKE '%L-DAC%' THEN  'L-DAC'
					WHEN REGIMEN LIKE '%ARSENIC_TRIOXIDE%' THEN 'ARSENIC_TRIOXIDE' 
					ELSE NULL
				END AS BACKBONE
				FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_BASIC_REGIMEN_BUSINESS_RULE_CHANGE_VAL_v2
									WHERE PATIENT_GID_RGMN IN
									(
										SELECT DISTINCT PATIENT_GID_RGMN
										FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_REGIMEN_REVAMP_PATIENT_COHORT_BUSINESS_RULE_CHANGE_VAL_v2
										WHERE PATIENT_INTENSITY_GROUP = 'IC_ELIG'
									)
			)A
		)A
	)
