-- VERIFIED QUERY REFERENCE
-- QUERY: AML_FINAL_ELIG_FLAGS
-- QUESTION: How is the AML eligibility flags table assembled?
-- PRIMARY_KBT: 5
-- SECONDARY_KBTS: 
-- DIALECT: Databricks / Spark SQL
-- PURPOSE: One row per patient with DX_LB, continuity (AML and VEN), VEN lookback, Dx-Tx gap, Tx-post-Dx, SCT, ARSENIC_FLG and legacy rule / new definition intensity.
-- DATA_SOURCE: SHA (SHA_PTD)
-- TABLES: Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_FST_DX_TX_TBL_BUSINESS_RULE_CHANGE_VAL; flag tables above; Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_PATS_COMB_LOT_TBL_BUSINESS_RULE_CHANGE_VAL; Z_ABV_CWS_MABI_ONC_ANALYTICS.PATIENT_INTENSITY_BASED_ON_AGE_N_PRODUCT; abv_val_ptd_onc_synd.sx_fact_curated_vw; px_fact_curated_vw; dx_fact_curated_vw
-- METRICS: sct_rate, bmb_rate
-- REUSABLE_COMPONENTS: flag joins, DX_TX_DIFF 0-60 days, SCT 51 Px/Sx codes + Z94.84/V42.82, ARSENIC_FLG COALESCE to 1
-- KNOWN_ISSUE: VEN_POST_DX_FLG and 2M_LF are not produced; derive them (context/domain/aml_eligibility_flags.md). Reads the un-suffixed new-definition table; AML_LOT_PATIENT_INTENSITY_LOT writes the _v2 name (OI-02). Writes Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_ELIG_FLAGS_FINAL_BUSINESS_RULE_CHANGE_VAL.
-- SOURCE: scripts/Notebooks (rendered with the notebook's table-name globals; CREATE TABLE wrappers removed so the reference only reads).
-- USE: Reuse fully when the request matches, or copy relevant components into a new working query.
-- ADAPTATION: Correct documented issues in the working query and disclose material changes; do not overwrite this reference.

SELECT PATS.*, 
CASE WHEN DX_LB_ELIG.ELIG_FLG = 1 THEN 1 ELSE 0 END AS DX_LB_ELIG_FLG,
--CASE WHEN TX_MX_LB_ELIG.ELIG_FLG_TX_MX = 1 THEN 1 ELSE 0 END AS TX_MX_LB_ELIG_FLG,
--CASE WHEN TX_RX_LB_ELIG.ELIG_FLG_TX_RX = 1 THEN 1 ELSE 0 END AS TX_RX_LB_ELIG_FLG,
CASE WHEN TX_TXL_M_ELIG.ELIG_FLG_TX_TXL_MX = 1 THEN 1 ELSE 0 END AS TX_TXL_MX_ELIG_FLG,
CASE WHEN TX_TXL_R_ELIG.ELIG_FLG_TX_TXL_RX = 1 THEN 1 ELSE 0 END AS TX_TXL_RX_ELIG_FLG,

CASE WHEN TX_MX_LB_ELIG_VEN.ELIG_FLG_TX_MX_VEN = 1 THEN 1 ELSE 0 END AS TX_MX_LB_ELIG_VEN_FLG,
CASE WHEN TX_RX_LB_ELIG_VEN.ELIG_FLG_TX_RX_VEN = 1 THEN 1 ELSE 0 END AS TX_RX_LB_ELIG_VEN_FLG,
CASE WHEN TX_TXL_M_ELIG_VEN.ELIG_FLG_TX_TXL_MX_VEN = 1 THEN 1 ELSE 0 END AS TX_TXL_MX_ELIG_VEN_FLG,
CASE WHEN TX_TXL_R_ELIG_VEN.ELIG_FLG_TX_TXL_RX_VEN = 1 THEN 1 ELSE 0 END AS TX_TXL_RX_ELIG_VEN_FLG,

CASE 
	WHEN DATEDIFF(to_date(FIRST_TX),to_date(FIRST_DX)) >= 0 AND DATEDIFF(to_date(FIRST_TX),to_date(FIRST_DX)) <= 60 THEN 1 
	ELSE 0 
END AS DX_TX_DIFF_FLG,
CASE WHEN FIRST_TX >= FIRST_DX THEN 1 ELSE 0 END AS TX_POST_DX_FLG,
TYPE.TYPE AS PATIENT_COHORT,
TYPE_UPDATED.PATIENT_INTENSITY_UPDATED AS PATIENT_COHORT_UPDATED,                          
CASE WHEN SCT_PX.SCT_PX_DATE >= FIRST_DX THEN 1 ELSE 0 END AS SCT_PX_FLG,
CASE WHEN SCT_DX.FIRST_SCT_DX >= FIRST_DX THEN 1 ELSE 0 END AS SCT_DX_FLG,
CASE WHEN SCT_PX.SCT_PX_DATE >= FIRST_DX OR SCT_DX.FIRST_SCT_DX >= FIRST_DX THEN 1 ELSE 0 END AS SCT_DX_PX_FLG,
COALESCE(ARSENIC_CHK.ARSENIC_FLG,1) AS ARSENIC_FLG --SHOULDN'T BE NULL FOR ANY PATIENT
FROM
(
	SELECT DISTINCT PATIENT_GID, FIRST_DX, FIRST_TX, LAST_TX
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_FST_DX_TX_TBL_BUSINESS_RULE_CHANGE_VAL
)PATS
---------AML TX ELIG FLAGS START----------------------
LEFT JOIN
(
	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_DX_LB_ELIG_TBL_BUSINESS_RULE_CHANGE_VAL
)DX_LB_ELIG
ON PATS.PATIENT_GID = DX_LB_ELIG.PATIENT_GID
--LEFT JOIN
--(
--	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG_TX_MX
--	FROM tx_lookback_elig
--)TX_MX_LB_ELIG
--ON PATS.PATIENT_GID = TX_MX_LB_ELIG.PATIENT_GID
--LEFT JOIN
--(
--	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG_TX_RX
--	FROM tx_lookback_elig_rx
---)TX_RX_LB_ELIG
--ON PATS.PATIENT_GID = TX_RX_LB_ELIG.PATIENT_GID
LEFT JOIN
(
	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG_TX_TXL_MX
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_TX_MX_TXL_ELIG_TBL_BUSINESS_RULE_CHANGE_VAL
)TX_TXL_M_ELIG
ON PATS.PATIENT_GID = TX_TXL_M_ELIG.PATIENT_GID
LEFT JOIN
(
	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG_TX_TXL_RX
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_TX_RX_TXL_ELIG_TBL_BUSINESS_RULE_CHANGE_VAL
)TX_TXL_R_ELIG
ON PATS.PATIENT_GID = TX_TXL_R_ELIG.PATIENT_GID
---------AML TX ELIG FLAGS END----------------------
---------VEN ELIG FLAGS START-----------------------
LEFT JOIN
(
	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG_TX_MX_VEN
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_VEN_TX_MX_LB_ELIG_TBL_BUSINESS_RULE_CHANGE_VAL
)TX_MX_LB_ELIG_VEN
ON PATS.PATIENT_GID = TX_MX_LB_ELIG_VEN.PATIENT_GID
LEFT JOIN
(
	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG_TX_RX_VEN
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_VEN_TX_RX_LB_ELIG_TBL_BUSINESS_RULE_CHANGE_VAL
)TX_RX_LB_ELIG_VEN
ON PATS.PATIENT_GID = TX_RX_LB_ELIG_VEN.PATIENT_GID
LEFT JOIN
(
	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG_TX_TXL_MX_VEN
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_VEN_TX_MX_TXL_ELIG_TBL_BUSINESS_RULE_CHANGE_VAL
)TX_TXL_M_ELIG_VEN
ON PATS.PATIENT_GID = TX_TXL_M_ELIG_VEN.PATIENT_GID
LEFT JOIN
(
	SELECT DISTINCT PATIENT_GID, 1 AS ELIG_FLG_TX_TXL_RX_VEN
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_LOT_PAT_VEN_TX_RX_TXL_ELIG_TBL_BUSINESS_RULE_CHANGE_VAL
)TX_TXL_R_ELIG_VEN
ON PATS.PATIENT_GID = TX_TXL_R_ELIG_VEN.PATIENT_GID


---------VEN ELIG FLAGS END---------------------------
LEFT JOIN
(
	SELECT PATIENT_GID, MIN(ARSENIC_FLG_INT) AS ARSENIC_FLG
	FROM
	(
		SELECT PATIENT_GID,
		CASE WHEN REGIMEN LIKE '%ARSENIC_TRIOXIDE%' THEN 0 ELSE 1 END AS ARSENIC_FLG_INT
		FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_PATS_COMB_LOT_TBL_BUSINESS_RULE_CHANGE_VAL
	)A
	GROUP BY 1
)ARSENIC_CHK
ON PATS.PATIENT_GID = ARSENIC_CHK.PATIENT_GID

---------PATIENT TYPE---------------------------
LEFT JOIN
(
	SELECT DISTINCT PATIENT_GID, TYPE
	FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.MABI_AML_PATS_COMB_LOT_TBL_BUSINESS_RULE_CHANGE_VAL
)TYPE
ON PATS.PATIENT_GID = TYPE.PATIENT_GID

LEFT JOIN 
(
           SELECT DISTINCT PATIENT_GID, PATIENT_INTENSITY_UPDATED
           FROM Z_ABV_CWS_MABI_ONC_ANALYTICS.PATIENT_INTENSITY_BASED_ON_AGE_N_PRODUCT       
)TYPE_UPDATED
ON PATS.PATIENT_GID = TYPE_UPDATED.PATIENT_GID
                                                 
                             
---------SCT DATES MAPPING---------------------------

LEFT JOIN
(
	select PATIENT_GID, MIN(TO_DATE(SCT_PX_DATE)) AS SCT_PX_DATE
	from 
	(

		SELECT PATIENT_SK AS PATIENT_GID, MIN(TO_DATE(CLAIM_DATE)) AS SCT_PX_DATE
		FROM abv_val_ptd_onc_synd.Sx_fact_curated_vw
		WHERE SURGICAL_code IN 
		(
			'38240','38241','38243','38242','30230G1','30230G2','30230G3','30230G4','30230U2','30230U3',
			'30230U4','30230Y1','30230Y2','30230Y3','30230Y4','30233G1','30233G2','30233G3','30233G4',
			'30233Y1','30233Y2','30233Y3','30233Y4','30240G1','30240G2','30240G3','30240G4','30240Y1',
			'30240Y2','30240Y3','30240Y4','30243G1','30243G2','30243G3','30243G4','30243Y1','30243Y2',
			'30243Y3','30243Y4','30250G1','30250Y1','30253G1','30253Y1','30260G1','30260Y1','30263G1',
			'30263Y1','4102','4103','4105','4108'
		)
		and source_flag  =  'SHA_PTD'
		and source_market  =  'ONC'
			
		GROUP BY 1

		union

		SELECT PATIENT_SK AS PATIENT_GID, MIN(TO_DATE(CLAIM_DATE)) AS SCT_PX_DATE
		FROM abv_val_ptd_onc_synd.px_fact_curated_vw
		WHERE procedure_code IN 
		(
			'38240','38241','38243','38242','30230G1','30230G2','30230G3','30230G4','30230U2','30230U3',
			'30230U4','30230Y1','30230Y2','30230Y3','30230Y4','30233G1','30233G2','30233G3','30233G4',
			'30233Y1','30233Y2','30233Y3','30233Y4','30240G1','30240G2','30240G3','30240G4','30240Y1',
			'30240Y2','30240Y3','30240Y4','30243G1','30243G2','30243G3','30243G4','30243Y1','30243Y2',
			'30243Y3','30243Y4','30250G1','30250Y1','30253G1','30253Y1','30260G1','30260Y1','30263G1',
			'30263Y1','4102','4103','4105','4108'
		)
		and source_flag  =  'SHA_PTD'
		and source_market  =  'ONC'
			
		GROUP BY 1

	)

	GROUP BY 1
)SCT_PX
ON PATS.PATIENT_GID = SCT_PX.PATIENT_GID

LEFT JOIN
(
	SELECT PATIENT_SK AS PATIENT_GID, MIN(CLAIM_DATE) AS FIRST_SCT_DX 
	FROM abv_val_ptd_onc_synd.dx_fact_curated_vw

	WHERE source_diagnosis_code_1 IN 
	(
	'Z94.84', 'V42.82'
	)
	GROUP BY 1
)SCT_DX
ON PATS.PATIENT_GID = SCT_DX.PATIENT_GID
